using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;

public class PlayerMovement : MonoBehaviour
{
    [Header("Movement")]
     

    public float groundDrag;

    public float jumpForce;
    public float jumpCooldown, kickCooldown;
    public float airMultiplier;

    public float defaultSpeed;
    float newLocalSpeed;
    float moveSpeed;

    bool readyToJump;
    bool speedOverride;
    [HideInInspector] public float walkSpeed;
    [HideInInspector] public float sprintSpeed;

    [Header("Keybinds")]
    

    [Header("Ground Check")]
    public float playerHeight;
    public LayerMask whatIsGround;
    bool grounded;

    public Transform orientation;

    float horizontalInput;
    float verticalInput;

    public bool movementLocked;
    Vector3 moveDirection;

    Rigidbody rb;

    private void Start()
    {
        rb = GetComponent<Rigidbody>();
        rb.freezeRotation = true;

       //readyToKick = true;
        readyToJump = true;
        speedOverride = false;
    }

    private void Update()
    {
        // ground checkolu
        grounded = Physics.Raycast(transform.position, Vector3.down, playerHeight * 0.5f + 0.3f, whatIsGround);
        
        if(speedOverride)
        {
            moveSpeed = newLocalSpeed;
        }
        else
        {
            moveSpeed = defaultSpeed;
        }

        MyInput();
        SpeedControl();

        if (movementLocked == false)
        {
            //Jump Input
            if (Input.GetButtonDown("Jump") && readyToJump && grounded)
            {

                readyToJump = false;

                Jump();

                Invoke(nameof(ResetJump), jumpCooldown);
            }

        }

        // handle drag
        if (grounded)
            rb.drag = groundDrag;
        else
            rb.drag = 0;
    }

    private void FixedUpdate()
    {

        if (movementLocked == false)
        {
            MovePlayer();
        }

    }

    private void MyInput()
    {
        horizontalInput = Input.GetAxisRaw("Horizontal");
        verticalInput = Input.GetAxisRaw("Vertical");

        // when to jump
        
    }

    private void MovePlayer()
    {
        // calculate movement direction
        moveDirection = orientation.forward * verticalInput + orientation.right * horizontalInput;

        // on ground
        if(grounded)
            rb.AddForce(moveDirection.normalized * moveSpeed * 10f, ForceMode.Force);

        // in air
        else if(!grounded)
            rb.AddForce(moveDirection.normalized * moveSpeed * 10f * airMultiplier, ForceMode.Force);

        
    }

    private void SpeedControl()
    {
        Vector3 flatVel = new Vector3(rb.velocity.x, 0f, rb.velocity.z);

        // limit velocity if needed
        if(flatVel.magnitude > moveSpeed)
        {
            Vector3 limitedVel = flatVel.normalized * moveSpeed;
            rb.velocity = new Vector3(limitedVel.x, rb.velocity.y, limitedVel.z);
        }
    }

    private void Jump()
    {
        // reset y velocity
        rb.velocity = new Vector3(rb.velocity.x, 0f, rb.velocity.z);

        rb.AddForce(transform.up * jumpForce, ForceMode.Impulse);
    }
    private void ResetJump()
    {
        readyToJump = true;
    }

    public void SpeedReduction(float newSpeed)
    {
        speedOverride = true;
        newLocalSpeed = newSpeed;
    }
    
    void Kick()
    {
        Debug.Log("Kick");
        //Kiciking logic
    }
    void ResetKick()
    {
       // readyToKick = true;
    }
}